/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type addressValidated = ContractEventLog<{
  _byWho: string;
  _forWHo: string;
  0: string;
  1: string;
}>;
export type allowanceChanged = ContractEventLog<{
  _forWho: string;
  _fromWho: string;
  _oldAmount: string;
  _newAmount: string;
  currency: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type validationIncreased = ContractEventLog<{
  _byWho: string;
  _forWHo: string;
  0: string;
  1: string;
}>;

export interface Allowance extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Allowance;
  clone(): Allowance;
  methods: {
    allowance(arg0: string): NonPayableTransactionObject<string>;

    usdAllowance(arg0: string): NonPayableTransactionObject<string>;

    validateMapping(arg0: string): NonPayableTransactionObject<boolean>;

    validations(arg0: string): NonPayableTransactionObject<string>;

    validateAddress(_address: string): NonPayableTransactionObject<void>;

    unvalidateAddress(_address: string): NonPayableTransactionObject<void>;

    addAllowance(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    addUsdAllowance(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    removeAllowance(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    removeAllowanceUsd(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    addressStatus(_address: string): NonPayableTransactionObject<boolean>;

    addressRemainingValidation(
      _address: string
    ): NonPayableTransactionObject<string>;

    addressAllowance(_address: string): NonPayableTransactionObject<string>;
  };
  events: {
    addressValidated(cb?: Callback<addressValidated>): EventEmitter;
    addressValidated(
      options?: EventOptions,
      cb?: Callback<addressValidated>
    ): EventEmitter;

    allowanceChanged(cb?: Callback<allowanceChanged>): EventEmitter;
    allowanceChanged(
      options?: EventOptions,
      cb?: Callback<allowanceChanged>
    ): EventEmitter;

    validationIncreased(cb?: Callback<validationIncreased>): EventEmitter;
    validationIncreased(
      options?: EventOptions,
      cb?: Callback<validationIncreased>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "addressValidated", cb: Callback<addressValidated>): void;
  once(
    event: "addressValidated",
    options: EventOptions,
    cb: Callback<addressValidated>
  ): void;

  once(event: "allowanceChanged", cb: Callback<allowanceChanged>): void;
  once(
    event: "allowanceChanged",
    options: EventOptions,
    cb: Callback<allowanceChanged>
  ): void;

  once(event: "validationIncreased", cb: Callback<validationIncreased>): void;
  once(
    event: "validationIncreased",
    options: EventOptions,
    cb: Callback<validationIncreased>
  ): void;
}
