/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type auctionStarted = ContractEventLog<{
  _tokenID: string;
  _startBid: string;
  _startingTime: string;
  _endingTime: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type bidMade = ContractEventLog<{
  _address: string;
  _tokenID: string;
  _lastBid: string;
  _currentBid: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type moneyReceived = ContractEventLog<{
  _amount: string;
  0: string;
}>;
export type newOwner = ContractEventLog<{
  _address: string;
  0: string;
}>;
export type pastBidWithdrawn = ContractEventLog<{
  _address: string;
  _value: string;
  0: string;
  1: string;
}>;

export interface Auctions extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Auctions;
  clone(): Auctions;
  methods: {
    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    auctionStarted(cb?: Callback<auctionStarted>): EventEmitter;
    auctionStarted(
      options?: EventOptions,
      cb?: Callback<auctionStarted>
    ): EventEmitter;

    bidMade(cb?: Callback<bidMade>): EventEmitter;
    bidMade(options?: EventOptions, cb?: Callback<bidMade>): EventEmitter;

    moneyReceived(cb?: Callback<moneyReceived>): EventEmitter;
    moneyReceived(
      options?: EventOptions,
      cb?: Callback<moneyReceived>
    ): EventEmitter;

    newOwner(cb?: Callback<newOwner>): EventEmitter;
    newOwner(options?: EventOptions, cb?: Callback<newOwner>): EventEmitter;

    pastBidWithdrawn(cb?: Callback<pastBidWithdrawn>): EventEmitter;
    pastBidWithdrawn(
      options?: EventOptions,
      cb?: Callback<pastBidWithdrawn>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "auctionStarted", cb: Callback<auctionStarted>): void;
  once(
    event: "auctionStarted",
    options: EventOptions,
    cb: Callback<auctionStarted>
  ): void;

  once(event: "bidMade", cb: Callback<bidMade>): void;
  once(event: "bidMade", options: EventOptions, cb: Callback<bidMade>): void;

  once(event: "moneyReceived", cb: Callback<moneyReceived>): void;
  once(
    event: "moneyReceived",
    options: EventOptions,
    cb: Callback<moneyReceived>
  ): void;

  once(event: "newOwner", cb: Callback<newOwner>): void;
  once(event: "newOwner", options: EventOptions, cb: Callback<newOwner>): void;

  once(event: "pastBidWithdrawn", cb: Callback<pastBidWithdrawn>): void;
  once(
    event: "pastBidWithdrawn",
    options: EventOptions,
    cb: Callback<pastBidWithdrawn>
  ): void;
}
