/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Approval = ContractEventLog<{
  owner: string;
  approved: string;
  tokenId: string;
  0: string;
  1: string;
  2: string;
}>;
export type ApprovalForAll = ContractEventLog<{
  owner: string;
  operator: string;
  approved: boolean;
  0: string;
  1: string;
  2: boolean;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type Transfer = ContractEventLog<{
  from: string;
  to: string;
  tokenId: string;
  0: string;
  1: string;
  2: string;
}>;
export type auctionStarted = ContractEventLog<{
  _tokenID: string;
  _startBid: string;
  _startingTime: string;
  _endingTime: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type bidMade = ContractEventLog<{
  _address: string;
  _tokenID: string;
  _lastBid: string;
  _currentBid: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type minted = ContractEventLog<{
  _to: string;
  _tokenId: string;
  0: string;
  1: string;
}>;
export type mintedForUsd = ContractEventLog<{
  _address: string;
  _amount: string;
  tokenId: string;
  0: string;
  1: string;
  2: string;
}>;
export type moneyReceived = ContractEventLog<{
  _amount: string;
  0: string;
}>;
export type newOwner = ContractEventLog<{
  _address: string;
  0: string;
}>;
export type pastBidWithdrawn = ContractEventLog<{
  _address: string;
  _value: string;
  0: string;
  1: string;
}>;

export interface Birds extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Birds;
  clone(): Birds;
  methods: {
    /**
     * See {IERC721-approve}.
     */
    approve(
      to: string,
      tokenId: number | string | BN
    ): NonPayableTransactionObject<void>;

    /**
     * See {IERC721-balanceOf}.
     */
    balanceOf(owner: string): NonPayableTransactionObject<string>;

    /**
     * See {IERC721-getApproved}.
     */
    getApproved(
      tokenId: number | string | BN
    ): NonPayableTransactionObject<string>;

    /**
     * See {IERC721-isApprovedForAll}.
     */
    isApprovedForAll(
      owner: string,
      operator: string
    ): NonPayableTransactionObject<boolean>;

    /**
     * See {IERC721Metadata-name}.
     */
    name(): NonPayableTransactionObject<string>;

    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>;

    /**
     * See {IERC721-ownerOf}.
     */
    ownerOf(tokenId: number | string | BN): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>;

    /**
     * See {IERC721-safeTransferFrom}.
     */
    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: number | string | BN
    ): NonPayableTransactionObject<void>;

    /**
     * See {IERC721-safeTransferFrom}.
     */
    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: number | string | BN,
      _data: string | number[]
    ): NonPayableTransactionObject<void>;

    /**
     * See {IERC721-setApprovalForAll}.
     */
    setApprovalForAll(
      operator: string,
      approved: boolean
    ): NonPayableTransactionObject<void>;

    /**
     * See {IERC165-supportsInterface}.
     */
    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;

    /**
     * See {IERC721Metadata-symbol}.
     */
    symbol(): NonPayableTransactionObject<string>;

    /**
     * See {IERC721Metadata-tokenURI}.
     */
    tokenURI(
      tokenId: number | string | BN
    ): NonPayableTransactionObject<string>;

    /**
     * See {IERC721-transferFrom}.
     */
    transferFrom(
      from: string,
      to: string,
      tokenId: number | string | BN
    ): NonPayableTransactionObject<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    setAddressPriceFeed(_address: string): NonPayableTransactionObject<void>;

    setUsdAddress(_address: string): NonPayableTransactionObject<void>;

    setWallet(_address: string): NonPayableTransactionObject<void>;

    getLatestPrice(): NonPayableTransactionObject<string>;

    flipSale(): NonPayableTransactionObject<void>;

    mintBird(_to: string): PayableTransactionObject<void>;

    minBirdForUSD(
      _to: string,
      _amount: number | string | BN
    ): PayableTransactionObject<void>;

    setBaseURI(baseURI: string): NonPayableTransactionObject<void>;

    withdrawUsd(): NonPayableTransactionObject<void>;

    withdrawn(): NonPayableTransactionObject<void>;

    auctionStart(
      _tokenID: number | string | BN,
      _startBid: number | string | BN,
      _endAuction: number | string | BN
    ): NonPayableTransactionObject<void>;

    makeBid(_tokenID: number | string | BN): PayableTransactionObject<void>;

    witdrawPassedBids(
      _value: number | string | BN,
      _to: string
    ): NonPayableTransactionObject<void>;

    withDrawFinalBid(
      _tokenID: number | string | BN,
      _to: string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    Approval(cb?: Callback<Approval>): EventEmitter;
    Approval(options?: EventOptions, cb?: Callback<Approval>): EventEmitter;

    ApprovalForAll(cb?: Callback<ApprovalForAll>): EventEmitter;
    ApprovalForAll(
      options?: EventOptions,
      cb?: Callback<ApprovalForAll>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    Transfer(cb?: Callback<Transfer>): EventEmitter;
    Transfer(options?: EventOptions, cb?: Callback<Transfer>): EventEmitter;

    auctionStarted(cb?: Callback<auctionStarted>): EventEmitter;
    auctionStarted(
      options?: EventOptions,
      cb?: Callback<auctionStarted>
    ): EventEmitter;

    bidMade(cb?: Callback<bidMade>): EventEmitter;
    bidMade(options?: EventOptions, cb?: Callback<bidMade>): EventEmitter;

    minted(cb?: Callback<minted>): EventEmitter;
    minted(options?: EventOptions, cb?: Callback<minted>): EventEmitter;

    mintedForUsd(cb?: Callback<mintedForUsd>): EventEmitter;
    mintedForUsd(
      options?: EventOptions,
      cb?: Callback<mintedForUsd>
    ): EventEmitter;

    moneyReceived(cb?: Callback<moneyReceived>): EventEmitter;
    moneyReceived(
      options?: EventOptions,
      cb?: Callback<moneyReceived>
    ): EventEmitter;

    newOwner(cb?: Callback<newOwner>): EventEmitter;
    newOwner(options?: EventOptions, cb?: Callback<newOwner>): EventEmitter;

    pastBidWithdrawn(cb?: Callback<pastBidWithdrawn>): EventEmitter;
    pastBidWithdrawn(
      options?: EventOptions,
      cb?: Callback<pastBidWithdrawn>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Approval", cb: Callback<Approval>): void;
  once(event: "Approval", options: EventOptions, cb: Callback<Approval>): void;

  once(event: "ApprovalForAll", cb: Callback<ApprovalForAll>): void;
  once(
    event: "ApprovalForAll",
    options: EventOptions,
    cb: Callback<ApprovalForAll>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "Transfer", cb: Callback<Transfer>): void;
  once(event: "Transfer", options: EventOptions, cb: Callback<Transfer>): void;

  once(event: "auctionStarted", cb: Callback<auctionStarted>): void;
  once(
    event: "auctionStarted",
    options: EventOptions,
    cb: Callback<auctionStarted>
  ): void;

  once(event: "bidMade", cb: Callback<bidMade>): void;
  once(event: "bidMade", options: EventOptions, cb: Callback<bidMade>): void;

  once(event: "minted", cb: Callback<minted>): void;
  once(event: "minted", options: EventOptions, cb: Callback<minted>): void;

  once(event: "mintedForUsd", cb: Callback<mintedForUsd>): void;
  once(
    event: "mintedForUsd",
    options: EventOptions,
    cb: Callback<mintedForUsd>
  ): void;

  once(event: "moneyReceived", cb: Callback<moneyReceived>): void;
  once(
    event: "moneyReceived",
    options: EventOptions,
    cb: Callback<moneyReceived>
  ): void;

  once(event: "newOwner", cb: Callback<newOwner>): void;
  once(event: "newOwner", options: EventOptions, cb: Callback<newOwner>): void;

  once(event: "pastBidWithdrawn", cb: Callback<pastBidWithdrawn>): void;
  once(
    event: "pastBidWithdrawn",
    options: EventOptions,
    cb: Callback<pastBidWithdrawn>
  ): void;
}
