/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type addressValidated = ContractEventLog<{
  _byWho: string;
  _forWHo: string;
  0: string;
  1: string;
}>;
export type allowanceChanged = ContractEventLog<{
  _forWho: string;
  _fromWho: string;
  _oldAmount: string;
  _newAmount: string;
  currency: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type moneyReceived = ContractEventLog<{
  _from: string;
  _amount: string;
  received: string;
  0: string;
  1: string;
  2: string;
}>;
export type moneySent = ContractEventLog<{
  _forWho: string;
  _amount: string;
  currency: string;
  0: string;
  1: string;
  2: string;
}>;
export type validationIncreased = ContractEventLog<{
  _byWho: string;
  _forWHo: string;
  0: string;
  1: string;
}>;

export interface Multisigned extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Multisigned;
  clone(): Multisigned;
  methods: {
    addAllowance(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    addUsdAllowance(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    addressAllowance(_address: string): NonPayableTransactionObject<string>;

    addressRemainingValidation(
      _address: string
    ): NonPayableTransactionObject<string>;

    addressStatus(_address: string): NonPayableTransactionObject<boolean>;

    allowance(arg0: string): NonPayableTransactionObject<string>;

    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>;

    removeAllowance(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    removeAllowanceUsd(
      _who: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    unvalidateAddress(_address: string): NonPayableTransactionObject<void>;

    usdAllowance(arg0: string): NonPayableTransactionObject<string>;

    validateAddress(_address: string): NonPayableTransactionObject<void>;

    validateMapping(arg0: string): NonPayableTransactionObject<boolean>;

    validations(arg0: string): NonPayableTransactionObject<string>;

    getBalance(): NonPayableTransactionObject<string>;

    getUsdBalance(): NonPayableTransactionObject<string>;

    setUsdAddress(_address: string): NonPayableTransactionObject<void>;

    withdrawMoney(
      _to: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    withdrawUSD(
      _to: string,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    addressValidated(cb?: Callback<addressValidated>): EventEmitter;
    addressValidated(
      options?: EventOptions,
      cb?: Callback<addressValidated>
    ): EventEmitter;

    allowanceChanged(cb?: Callback<allowanceChanged>): EventEmitter;
    allowanceChanged(
      options?: EventOptions,
      cb?: Callback<allowanceChanged>
    ): EventEmitter;

    moneyReceived(cb?: Callback<moneyReceived>): EventEmitter;
    moneyReceived(
      options?: EventOptions,
      cb?: Callback<moneyReceived>
    ): EventEmitter;

    moneySent(cb?: Callback<moneySent>): EventEmitter;
    moneySent(options?: EventOptions, cb?: Callback<moneySent>): EventEmitter;

    validationIncreased(cb?: Callback<validationIncreased>): EventEmitter;
    validationIncreased(
      options?: EventOptions,
      cb?: Callback<validationIncreased>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "addressValidated", cb: Callback<addressValidated>): void;
  once(
    event: "addressValidated",
    options: EventOptions,
    cb: Callback<addressValidated>
  ): void;

  once(event: "allowanceChanged", cb: Callback<allowanceChanged>): void;
  once(
    event: "allowanceChanged",
    options: EventOptions,
    cb: Callback<allowanceChanged>
  ): void;

  once(event: "moneyReceived", cb: Callback<moneyReceived>): void;
  once(
    event: "moneyReceived",
    options: EventOptions,
    cb: Callback<moneyReceived>
  ): void;

  once(event: "moneySent", cb: Callback<moneySent>): void;
  once(
    event: "moneySent",
    options: EventOptions,
    cb: Callback<moneySent>
  ): void;

  once(event: "validationIncreased", cb: Callback<validationIncreased>): void;
  once(
    event: "validationIncreased",
    options: EventOptions,
    cb: Callback<validationIncreased>
  ): void;
}
