/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface NestV1 extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): NestV1;
  clone(): NestV1;
  methods: {
    Bird(): NonPayableTransactionObject<string>;

    stakes(arg0: string): NonPayableTransactionObject<{
      tokenId: string;
      amount: string;
      timestamp: string;
      0: string;
      1: string;
      2: string;
    }>;

    stakingTime(arg0: string): NonPayableTransactionObject<string>;

    stake(
      _tokenId: number | string | BN,
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    unstake(): NonPayableTransactionObject<void>;

    onERC1155Received(
      operator: string,
      from: string,
      id: number | string | BN,
      value: number | string | BN,
      data: string | number[]
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
